os: Visual Studio 2015

version: "{build}"

environment:
  matrix:
    - channel: stable
      host: x86_64-pc-windows-msvc
      target: x86_64-pc-windows-msvc
    - channel: stable
      host: x86_64-pc-windows-msvc
      target: x86_64-pc-windows-gnu
      mingw: x86_64-6.3.0-posix-seh-rt_v5-rev1
    - channel: nightly
      host: x86_64-pc-windows-msvc
      target: x86_64-pc-windows-msvc

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %host%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - if not %target% == %host% rustup target add %target%
  - rustc -vV && cargo -vV

  # Because that MSBUild does not support path longer than MAX_PATH
  # (https://github.com/Microsoft/msbuild/issues/53),
  # we use ninja to build.
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=%PATH%;C:\projects\deps\ninja
  - ninja --version

  - if defined mingw set PATH=%PATH:C:\Program Files\Git\usr\bin;=%;C:\mingw-w64\%mingw%\mingw64\bin
  - if defined mingw gcc --version

build:
  parallel: true
  verbosity: minimal

before_build:
  - git submodule update --init

build_script:
  - cargo build --verbose --target %target%

test_script:
  - cargo test --verbose --target %target%
