os: Visual Studio 2015

version: "{build}"

environment:
  matrix:
    - channel: stable
      host: x86_64-pc-windows-msvc
      target: x86_64-pc-windows-msvc
    - channel: stable
      host: x86_64-pc-windows-msvc
      target: x86_64-pc-windows-gnu
      mingw: x86_64-6.3.0-posix-seh-rt_v5-rev1
    - channel: nightly
      host: x86_64-pc-windows-msvc
      target: x86_64-pc-windows-msvc

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %host%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - if not %target% == %host% rustup target add %target%
  - if defined mingw set PATH=%PATH:C:\Program Files\Git\usr\bin;=%;C:\mingw-w64\%mingw%\mingw64\bin
  - rustc -vV && cargo -vV && if defined mingw gcc --version

build:
  parallel: true
  verbosity: minimal

before_build:
  - git submodule update --init

build_script:
  - cargo build --verbose --target %target%

test_script:
  - cargo test --verbose --target %target%
